### ISSUE TITLE
Activity planner

### ISSUE THREAD

**Issue by a-jaxell** [a-jaxell/guidernas-guide#1]
The Activity planner is a major part of the app, It is one of the core feature Guides use to organize activities, expeditions or events for their Customers. 

This Epic covers the different parts of designing an interface for a Guide to use when creating a new activity.
Activities can be of different types(hiking, canoeing, expedition). Some are an 3-hour rock climbing course, others might be a multi-day trip across the swedish-norwegian border during winter. 

Guides are meant to use this tool to organize information about the activity easily accessible to themselves and their potential Customers. Information about the activity can be length in hours, distance traveled, what route on a map, number of participants etc. 

## Use Cases
- A guide want to create a new hiking trip.
- A guide want to add description of one of their trips
- A guide wants to change the number of maximum Customers on one of their trips.
- A guide wants to see how many people have paid for themself. 
- A guide wants to send a message to all of the Customers on one of their trips. 

## Terminology
Guides - The professional users of this app, who use it to plan their activities for a customer.
Customer - A person that is interested in an activity that a Guide provides/hosts.
Activity - An (outdoor) activity varying type. Has a type

## Wireframe

[Activity planner on figma ](https://www.figma.com/file/o3flAoFZScNtyzQOL6h8vC/Wireframe?type=design&node-id=20-2&mode=design&t=tg0nRpU2zvUU79hh-0)

## Tasks
- [x] #4
- [x] #5
- [ ] Create functionality to edit activities
- [ ]  Implement functionality for Guides to send messages to Customers
- [ ]  Integrate mapping tools for route planning (Route Planner)
