### ISSUE TITLE
Add API methods in Next.js

### ISSUE THREAD

**Issue by a-jaxell** [a-jaxell/guidernas-guide#10]
Since the API is run separately in its own container I need to create methods for various operations needed in the frontend.

### Tasks

- [x] Initially add create/edit methods in Next.js that fetches data from the API application 
- [x] Keep methods in a separate file
- [x] Add more methods as you go
