### ISSUE TITLE
Landing page for login and sign up

### ISSUE THREAD

**Issue by a-jaxell** [a-jaxell/guidernas-guide#14]
- As a user I want to log in
- As a user I want to sign up.

This is the start of the app, should handle login and account signup.
To simplify account handling use firebase auth to create user accounts and handle login.

### Tasks

- [x] A user should be able to sign in
- [x] A user should be able to sign up
- [x] Use firebase Auth

### Wireframe

![Image](https://github.com/a-jaxell/guidernas-guide/assets/97404672/82799274-3f7d-45d1-b604-5cfb3c626320)
