### ISSUE TITLE
Community feature

### ISSUE THREAD

**Issue by a-jaxell** [a-jaxell/guidernas-guide#2]
The community feature makes customers, guides and organizations able to connect with each other.

There should be different ways to communicate, both passively (Putting up a post looking for others to join on a hike) and actively (messages from users or guides of events that an user is participating in).

Sharing your experiences and connecting with other Customers and Guides.

## Terminology

* Customer - A person wanting to use the services of Guides and/or Organizations.
* Guide - Single individual in the Outdoor business. Can be a part of an Organization
* Organization - A Company or other Actor in the Outdoor business. Normally larger than 1 individual.

## Use Cases 

- A Customer wants to make a post about an activity they were a part of.
- A Guide want to market their activities
- A Customer wants to connect with another Customer
- A Guide wants to connect with another Guide
- A Guide wants to reply to a Customers post

## Tasks
- [ ] Implement a messaging feature.
- [ ] Create a database model for a Message 
- [ ] Design for community (What is meant to be shared and how?)
