### ISSUE TITLE
Third Party Certification

### ISSUE THREAD

**Issue by a-jaxell** [a-jaxell/guidernas-guide#22]
In different sports and situations a certain certificate of knowledge or training might be good to ensure to Customers that Guides are proficient in their profession. Example certificates could be Wilderness Advanced First Aid/ WFR, Fjällledarnormen, an exam from a Trade School. Or certificates to a specific branch of outdoor sports such as IMGA Mountain guide, Climbing certificate.

Certificates arent just solely for guides, It could be benificiary for guides to check wether customers have certificates or not.
And limit access to their products based on customer experience/certificates. (As for a skitouring guides might want to limit customers to those which has taken courses in avalanche safety)

This would require validation against an external API or manual check against the correct provider of a certain certificate and the validated by hand. So depending on what certificate it might be more or less hard. 
The idea is to make validation more accessible to Customers. (Being able to click and check if a Guide has a validated certificate)

One idea is to design this as a separate entity from the App and supply validation to third parties.
To provide certification validation for Guides, Customers and Organizations.

## Use cases
- A Guide want to make sure all of their clients for a certain trip has the correct certifications for ski touring. 
- A Customer wants to make sure a certain guide have knowledge about first aid if something would happen on their hike.
- An Admin wants to validate that Guides claiming to be Mountain guides actually are mountain guides.
- A Customer wants to make sure that a Kayak Guide has the correct whitewater certificate.

## Terminology

- Certificate - Proof of training in specific branch of outdoor sports. (Climbing, Kayaking, Skiing)
- Guide - Can hold specific certificates for guides. (Mountain guide, kayak guide, Mountain Leader, Fjällledare)
- Customer - Can hold certificates that might not be limited to a person not working in the outdoor industry. (First Aid, HLR, green card/climbing, Sve-LAV)

## Tasks 

- [x] Design Database Model for Certifications
- [ ] Admin interface for adding, managing and validating certifications.
- [ ] User interface for adding and managing certifications. And request to validate.
- [ ] Research pros/cons for certification validation.
