### ISSUE TITLE
Update Controller for creating new tasks

### ISSUE THREAD

**Issue by a-jaxell** [a-jaxell/guidernas-guide#24]
When creating new tasks from the frontend the controller is returning Activities with
certain properties set to null.

This is because these are not being set on creation. 

### Tasks

- [ ] Update `ActivityCreateDto` to accept values for `title`
- [ ] Update ActivityController to set `title` values on creation of new entities
- [ ] Create schema in `db.migration`
